
 # Name: Michael Kausch
 # Assignment: xylab10 - Midterm
 # Class: CMPS 3350
 # Professor: Gordon
 # Date: 3/28/23
 
all: lab10

lab10:	xylab10.cpp xyprime.cpp xyprime.h
	g++ xylab10.cpp xyprime.cpp -Wall -olab10

clean:
	rm -f lab10

run:
	./lab10 100000