
 # Name: Michael Kausch
 # Assignment: xylab12
 # Class: CMPS 3350
 # Professor: Gordon
 # Date: 4/18/23
 
all: lab12 utest

lab12:	xylab12.cpp
	g++ xylab12.cpp -Wall -olab12

utest:	unit_test.cpp
	g++ unit_test.cpp -Wall -outest

clean:
	rm -f lab12 utest
