
 # Name: Michael Kausch
 # Assignment: xylab7
 # Class: CMPS 3350
 # Professor: Gordon
 # Date: 3/7/23
 
all: lab7

lab7:	xylab7.cpp 
	g++ xylab7.cpp -Wall -olab7

lab7wip: xylab7wip.cpp sort7.cpp
	g++ xylab7wip.cpp sort7.cpp -Wall -olab7wip

clean:
	rm -f lab7
