
 # Name: Michael Kausch
 # Assignment: xylab7
 # Class: CMPS 3350
 # Professor: Gordon
 # Date: 3/7/23
 
all: lab7

lab7:	xylab7.cpp sort7.cpp
	g++ xylab7.cpp sort7.cpp -Wall -olab7

clean:
	rm -f lab7
