
 # Name: Michael Kausch
 # Assignment: xylab6b
 # Class: CMPS 3350
 # Professor: Gordon
 # Date: 4/28/23
 
all: lab6b

lab6b:	xylab6b.cpp substring.cpp
	g++ xylab6b.cpp substring.cpp -Wall -olab6b 

clean:
	rm -f lab6b
